

[username]
show_always = true
style_user = "bright-red"

[hostname]
ssh_only = false
style = "bright-red"

[env_var]
variable = "SHELL"
style = "bright-yellow"

[directory]
truncation_length = 5
prefix = ""
style = "bright-cyan"
