

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
prefix = "in "
style = "bold cyan"

[env_var]
variable = "SHELL"
style = "bold yellow"
default = "unknown shell"

[git_branch]
style = "bold cyan"

[git_status]
disabled = true

[hostname]
ssh_only = false
style = "bold red"
prefix = "["
suffix = "]"

[username]
show_always = true
style_user = "bold red"
