

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
# blue
style  = "fg:#40e0d0"
format = "[$path]($style) "

[git_branch]
# yellow
style  = "fg:#ffd700"
format = "[$symbol$branch]($style) "

[git_status]
disabled = true

[hostname]
ssh_only = false
# red
style    = "fg:#ff6347"
format   = "[$hostname]($style) "

[username]
show_always = true
# red
style_user  = "fg:#ff6347"
format      = "[$user@]($style)"

[golang]
# blue
style  = "fg:#40e0d0"
format = "via [go $version]($style)"
